#!/bin/bash

# If we are on the master branch
if [ 'git branch'="master" ]
then
  # Build CSS and JS
  npm run build

  # 
  git config user.email "travis@knowledge-map.org"
  git config user.name "travis"

  # Commit the builds
  git add dist
  #git commit -m "Updating distribution files"
  
  # Update the version
  # also update the git version tags
  npm version patch

  # Update the repo
  git push https://github.com/knowledge-map/cartographer.git
fi
