#!/bin/bash

# If we are on the master branch
if [ 'git branch'="master" ]
then
  # Build CSS and JS
  npm run build

  # Add travis identification
  git config user.email "travis@knowledge-map.org"
  git config user.name "travis"

  # Commit the builds
  git add dist/*
  NEW_DISTS=$?
  
  # If there are new distribution files
  if [ $NEW_DISTS -eq 0 ]
  then
    # Update the version
    # also update the git version tags
    npm version patch

    # Update the repo
    git push https://github.com/knowledge-map/cartographer.git
  fi
fi
